const fs = require('fs');
const feedPath = 'lib/feed-storage.ts';
const guildPath = 'app/components/GuildFeed.tsx';
const feed = fs.readFileSync(feedPath, 'utf8');
const guild = fs.readFileSync(guildPath, 'utf8');
console.log('--- FEED START ---');
console.log(feed.slice(0, 1200));
console.log('--- FEED MID ---');
console.log(feed.slice(1200, 2400));
console.log('--- GUILD START ---');
console.log(guild.slice(0, 1200));
console.log('--- GUILD MID ---');
console.log(guild.slice(1200, 2400));
console.log('--- GUILD END ---');
console.log(guild.slice(2400, 3200));
