const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname);
const feedPath = path.join(root, 'lib', 'feed-storage.ts');
const guildPath = path.join(root, 'app', 'components', 'GuildFeed.tsx');
const feedText = fs.readFileSync(feedPath, 'utf8');
console.log('feed length', feedText.length);
console.log('contains const SEED', feedText.includes('const SEED: GuildCompletion[] = ['));
console.log('contains feedOriginal', feedText.includes('id: "seed-4"'));
console.log('index of seed-4', feedText.indexOf('id: "seed-4"'));
console.log('index of parse line', feedText.indexOf('const parsed = JSON.parse(raw) as GuildCompletion[];'));
const guildText = fs.readFileSync(guildPath, 'utf8');
console.log('guild length', guildText.length);
console.log('contains compact line', guildText.includes('const displayItems = compact ? items.slice(0, 2) : items;'));
console.log('contains fallback original', guildText.includes('e.currentTarget.src = "data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'100%25\' height=\'100%25\'%3E%3Crect width=\'100%25\' height=\'100%25\' fill=\'%23020617\'/%3E%3Ctext x=\'50%25\' y=\'50%25\' font-family=\'monospace\' font-size=\'14\' font-weight=\'bold\' fill=\'%2322d3ee\' text-anchor=\'middle\' dominant-baseline=\'middle\'%3E[ DATA LINK BROKEN ]%3C/text%3E%3C/svg%3E";'));
console.log('index of fierce display', guildText.indexOf('const displayItems = compact ? items.slice(0, 2) : items;'));
console.log('index of fallback', guildText.indexOf('e.currentTarget.src = "data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'100%25\' height=\'100%25\'%3E%3Crect width=\'100%25\' height=\'100%25\' fill=\'%23020617\'/%3E%3Ctext x=\'50%25\' y=\'50%25\' font-family=\'monospace\' font-size=\'14\' font-weight=\'bold\' fill=\'%2322d3ee\' text-anchor=\'middle\' dominant-baseline=\'middle\'%3E[ DATA LINK BROKEN ]%3C/text%3E%3C/svg%3E";'));
console.log('first 240 guild snippet');
console.log(guildText.slice(80, 260));
